# Mod Loading Info
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

# VillageCraft 3 Essentials Conifg
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

# Dependency for NeoForge
[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

# Dependency for Minecraft
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"